# Generated by Django 4.2.8 on 2023-12-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
